<?php
return [
    //Fire Nation
    [
        'name' => 'Agni Drill Gloves',
        'price' => 1999.00,
        'stock' => 20,
        'stock_quantity' => 20,
        'image_url' => '',
        'description' => 'Specialized fire-resistant gloves for breathing synchronization and strike training.',
    ],
    [
        'name' => 'Breath of Sozin Mask',
        'price' => 1499.00,
        'stock' => 20,
        'stock_quantity' => 20,
        'image_url' => '',
        'description' => 'A martial arts breathing mask infused with warming herbs.',
    ],
    [
        'name' => 'Blazing Kata Scrolls',
        'price' => 999.00,
        'stock' => 20,
        'stock_quantity' => 20,
        'image_url' => '',
        'description' => 'Advanced firebending sequences for agility, footwork, and controlled bursts.',
    ],
    [
        'name' => 'Flame Arc Bands',
        'price' => 1249.00,
        'stock' => 20,
        'stock_quantity' => 20,
        'image_url' => '',
        'description' => 'Wrist bands weighted for training rapid strikes and whip motions.',
    ],
    [
        'name' => 'Dancing Dragon Silks',
        'price' => 2499.00,
        'stock' => 20,
        'stock_quantity' => 20,
        'image_url' => '',
        'description' => 'Traditional practice robes for dual form routines.',
    ],
    [
        'name' => 'Inferno Training Mat',
        'price' => 2499.00,
        'stock' => 20,
        'stock_quantity' => 20,
        'image_url' => '',
        'description' => 'High-grip mat with flame-flow pattern to guide stance work.',
    ],

    //Water Tribe
    [
        'name' => 'Flowform Sash',
        'price' => 1499.00,
        'stock' => 20,
        'stock_quantity' => 20,
        'image_url' => '',
        'description' => 'A cloth band worn around the waist for balance and motion awareness.',
    ],
    [
        'name' => 'Moon Pull Stones',
        'price' => 749.00,
        'stock' => 20,
        'stock_quantity' => 20,
        'image_url' => '',
        'description' => 'Two small orbs used to train fluid wrist and arm rotations.',
    ],
    [
        'name' => 'Tidal Stance Pads',
        'price' => 1199.00,
        'stock' => 20,
        'stock_quantity' => 20,
        'image_url' => '',
        'description' => 'Soft training pads placed under feet for shifting and sliding exercises.',
    ],
    [
        'name' => 'Spirit Current Wraps',
        'price' => 799.00,
        'stock' => 20,
        'stock_quantity' => 20,
        'image_url' => '',
        'description' => 'Arm wraps infused with sea salt and lavender for calming flow practice.',
    ],
    [
        'name' => 'Healing Circle Mat',
        'price' => 2199.00,
        'stock' => 20,
        'stock_quantity' => 20,
        'image_url' => '',
        'description' => 'A reflective training mat used in group bending drills or healing rituals.',
    ],
    [
        'name' => 'Glacial Edge Fan',
        'price' => 1299.00,
        'stock' => 20,
        'stock_quantity' => 20,
        'image_url' => '',
        'description' => 'A lightweight practice fan used to simulate ice slicing and wave forms.',
    ],

    //Air Nomads
    [
        'name' => 'Spiral Motion Bands',
        'price' => 1599.00,
        'stock' => 20,
        'stock_quantity' => 20,
        'image_url' => '',
        'description' => 'Elastic training bands used to encourage wide circular movements.',
    ],
    [
        'name' => 'Whisper Cloak',
        'price' => 3000.00,
        'stock' => 20,
        'stock_quantity' => 20,
        'image_url' => '',
        'description' => 'Extremely lightweight hooded robe that responds to movement and airflow.',
    ],
    [
        'name' => 'Cyclone Steps Mat',
        'price' => 1899.00,
        'stock' => 20,
        'stock_quantity' => 20,
        'image_url' => '',
        'description' => 'A circular footwork mat used to train directional change and evasion.',
    ],
    [
        'name' => 'Monk Gyatso Breath Bell',
        'price' => 1199.00,
        'stock' => 20,
        'stock_quantity' => 20,
        'image_url' => '',
        'description' => 'A bell that rings only with steady exhalation through a breathing tube.',
    ],
    [
        'name' => 'Glider Staff Trainer',
        'price' => 1699.00,
        'stock' => 20,
        'stock_quantity' => 20,
        'image_url' => '',
        'description' => 'A shortened, padded version of the iconic glider staff.',
    ],
    [
        'name' => 'Void Meditation Ord',
        'price' => 999.00,
        'stock' => 20,
        'stock_quantity' => 20,
        'image_url' => '',
        'description' => 'A lightweight sphere used during balance meditation and Ba Gua circles.',
    ],

    //Earth Kingdom
    [
        'name' => 'Tremor Grounding Sandals',
        'price' => 2099.00,
        'stock' => 20,
        'stock_quantity' => 20,
        'image_url' => '',
        'description' => 'Weighted shoes designed to enhance stance practice and earth connection.',
    ],
    [
        'name' => 'Stone Core Belt',
        'price' => 1599.00,
        'stock' => 20,
        'stock_quantity' => 20,
        'image_url' => '',
        'description' => 'A training belt that provides feedback on hip alignment during stances.',
    ],
    [
        'name' => 'Seismic Focus Rods',
        'price' => 1199.00,
        'stock' => 20,
        'stock_quantity' => 20,
        'image_url' => '',
        'description' => 'Handheld rods for training punching accuracy and resistance.',
    ],
    [
        'name' => 'Pillar Stance Board',
        'price' => 1499.00,
        'stock' => 20,
        'stock_quantity' => 20,
        'image_url' => '',
        'description' => 'A rigid board with stone patterns to guide foot spacing.',
    ],
    [
        'name' => 'Ironroot Arm Weights',
        'price' => 1399.00,
        'stock' => 20,
        'stock_quantity' => 20,
        'image_url' => '',
        'description' => 'Forearm bands with internal sand-fill for slow, controlled bending drills.',
    ],
    [
        'name' => 'Badgermole Rhythm Drum',
        'price' => 1299.00,
        'stock' => 20,
        'stock_quantity' => 20,
        'image_url' => '',
        'description' => 'A pulse drum used during seismic sensing and earth-rhythm meditation.',
    ]
];
